import styled from "@emotion/styled";
import { Box } from "@mui/system";

const before = {
  content: "''",
  backgroundAttachment: "scroll",
  backgroundClip: "border-box",
  backgroundColor: "rgb(69, 39, 160)",
  backgroundImage: "none",
  backgroundOrigin: "padding-box",
  backgroundPositionX: "0%",
  backgroundPositionY: "0%",
  backgroundRepeatX: "repeat",
  backgroundRepeatY: "repeat",
  backgroundSize: "auto",
  borderBottomLeftRadius: "50%",
  borderBottomRightRadius: "50%",
  borderTopLeftRadius: "50%",
  borderTopRightRadius: "50%",
  boxSizing: "border-box",
  color: "rgb(255, 255, 255)",
  display: "block",
  fontFamily: "Roboto, sans-serif",
  fontSize: "14px",
  fontWeight: "400",
  height: "210px",
  lineHeight: "18.676px",
  opacity: "0.5",
  position: "absolute",
  right: "-15px",
  top: "-125px",
  width: "210px",
};

const after = {
  backgroundAttachment: "scroll",
  backgroundClip: "border-box",
  backgroundColor: "rgb(69, 39, 160)",
  backgroundImage: "none",
  backgroundOrigin: "padding-box",
  backgroundPositionX: "0%",
  backgroundPositionY: "0%",
  backgroundRepeatX: "repeat",
  backgroundRepeatY: "repeat",
  backgroundSize: "auto",
  borderBottomLeftRadius: "50%",
  borderBottomRightRadius: "50%",
  borderTopLeftRadius: "50%",
  borderTopRightRadius: "50%",
  boxSizing: "border-box",
  color: "rgb(255, 255, 255)",
  content: "''",
  display: "block",
  fontFamily: "Roboto, sans-serif",
  fontSize: "14px",
  fontWeight: "400",
  height: "210px",
  lineHeight: "18.676px",
  position: "absolute",
  right: "-95px",
  textSizeAdjust: "100%",
  top: "-85px",
  width: "210px",
  webkitFontSmoothing: "antialiased",
  zIndex: "1",
};

export const CahrtConstructorWrapper = styled(Box)((props) => ({
  width: "100%",
  height: "100%",
  padding: "16px",
  display: "flex",
  flexDirection: "column",
  backgroundColor: "#5e35b1",
  borderRadius: "12px",
  overflow: "hidden",
  position: "relative",
  "&::before": before,
  "&::after": after,
}));

export const DrawerHeader = styled("div")(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  justifyContent: "flex-end",
  padding: theme.spacing(0, 1),
  // necessary for content to be below app bar
  ...theme.mixins.toolbar,
}));
